export const API_INPUT = {
  GENERATE_TOKEN: Symbol.for('GENERATE_TOKEN_INPUT'),
  SIGN_UP: Symbol.for('SIGN_UP_INPUT'),
  VALIDATE_EMAIL: Symbol.for('VALIDATE_EMAIL_INPUT'),
  VALIDATE_USERNAME: Symbol.for('VALIDATE_USERNAME_INPUT'),
};
