export const API_OUTPUT = {
  GENERATE_TOKEN: Symbol.for('GENERATE_TOKEN_OUTPUT'),
  SIGN_UP: Symbol.for('SIGN_UP_OUTPUT'),
  VALIDATE_EMAIL: Symbol.for('VALIDATE_EMAIL_OUTPUT'),
  VALIDATE_USERNAME: Symbol.for('VALIDATE_USERNAME_OUTPUT'),
};
