import { TYPES } from '@shared-library/const';

export const API_TYPES = {
  APPLICATION: TYPES.APPLICATION,
  HTTP: TYPES.HTTP,
  ROUTER: TYPES.ROUTER,
  MIDDLEWARE: TYPES.MIDDLEWARE,
  LOGGER: TYPES.LOGGER,
  ROUTER_VALIDATOR: TYPES.ROUTER_VALIDATOR,
  CONTROLLER: TYPES.CONTROLLER,
  USECASE: TYPES.USECASE,
  SCHEMA: TYPES.SCHEMA,
  TABLE: TYPES.TABLE,
  SEQUELIZE: TYPES.SEQUELIZE,
  REPOSITORY: TYPES.REPOSITORY,
  MAPPER: TYPES.MAPPER,
  JWT_HELPER: TYPES.JWT_HELPER,
  PASSWORD_HELPER: TYPES.PASSWORD_HELPER

};
